---
# tasks file for roles/mywebsite
- import_tasks: installingnginx.yml
  notify:
    - start-nginx



- import_tasks: configcopy.yml
  notify:
     - restart-nginx
- meta: flush_handlers

- import_tasks: confdcopy.yml
  notify:
     - restart-nginx

- import_tasks: htmlcopy.yml
  notify:
     - restart-nginx